//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public string AspNetUser { get; set; }
        public int Answer { get; set; }
        public bool Likes { get; set; }
    
        public virtual Answer Answer1 { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
