//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenOrder
    {
        public int Id { get; set; }
        public string Buyer { get; set; }
        public int NumTokens { get; set; }
        public int Price { get; set; }
        public int TokenPackage { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual TokenPackage TokenPackage1 { get; set; }
    }
}
